### ISSUE TITLE
Problem when building

### ISSUE THREAD

**Issue by AnibalDuarte** [ar27111994/Mosaico-CodeIgniter-Ion-Auth#1]
When I run grunt on /mosaico this error shows up:

(node:4048) ExperimentalWarning: The http2 module is an experimental API.
Running "bowercopy:libs" (bowercopy) task
bower not-cached git://github.com/bago/knockout.wrap.git#mosaico
bower resolve git://github.com/bago/knockout.wrap.git#mosaico
bower not-cached git://github.com/bago/colorpicker.git#mosaico
bower resolve git://github.com/bago/colorpicker.git#mosaico
bower cached git://github.com/gvas/knockout-jqueryui.git#2.2.3
bower validate 2.2.3 against git://github.com/gvas/knockout-jqueryui.git#~2.2.3
bower cached git://github.com/Automattic/juice.git#3.0.1
bower validate 3.0.1 against git://github.com/Automattic/juice.git#~3.0.1
bower cached git://github.com/ZiadJ/knockoutjs-reactor.git#1.3.9
bower validate 1.3.9 against git://github.com/ZiadJ/knockoutjs-reactor.git#~1.3.9
bower cached git://github.com/kamicane/slick.git#1.12.2
bower validate 1.12.2 against git://github.com/kamicane/slick.git#~1.12.2
bower checkout mosaico
bower checkout mosaico
bower resolved git://github.com/bago/knockout.wrap.git#6d45d1e282
bower invalid-meta The "main" field cannot contain minified files
bower invalid-meta The "main" field cannot contain minified files
bower resolved git://github.com/bago/colorpicker.git#8614d91c6f
**Fatal error: Request to https://bower.herokuapp.com/packages/jquery failed with 502**

**Comment by AnibalDuarte** [comment]
Plus, when I try to run the /email_templates an database connection error shows up:

**Message: mysqli::real_connect(): (HY000/1045): Access denied for user 'arcom_ar'@'localhost' (using password: YES)**

But I even locate the string 'arcom_ar' in the entire project.

**Comment by ar27111994** [comment]
Hi, make sure that you have updated the database credentials in your copy. Also I have pushed fix for `grunt` error. Please re-clone this repo and build again.

**Comment by AnibalDuarte** [comment]
Build problem solved.

The database problem wasn't on my enviroment, but on the online example. The default view points for it.

The absent **.htaccess** it's causing routing errors on the base install, too.
