### ISSUE TITLE
Problem on e-mail image opening

### ISSUE THREAD

**Issue by AnibalDuarte** [ar27111994/Mosaico-CodeIgniter-Ion-Auth#2]
First: when implementing the script on my own CI I've found an issue: 

On mosaico/editor.php in the line 35 and mosaico/index.php at line 98 there is a Javascript var called **server** setted up to be **'/'**. The problem is when the e-mail HTML is builded the relative path can be problematic as the HTML isn't loaded on the server itself, but inside the e-mail reader. Some readers can't load this kind of path. The fix to it is just set up the URL base path of the website in this var, like:

`var server = '<?php echo 'http'.(!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off' || $_SERVER['SERVER_PORT'] == 443?'s':'').'://'.$_SERVER['SERVER_NAME'].'/'); ?>';`

Plus, in **Email_Templates** controller there is a "session checker" on ProcessImgRequest function. It blocks the image loading for the e-mail receivers, since the e-mail client isn't logged in. Just cut off the session checkers to this function and everything will run smoothly.

**Comment by ar27111994** [comment]
Hi, thanks for the info. Can you create a pr to master for this change? I will be happy to test it and merge.

**Comment by ar27111994** [comment]
I checked the above mentioned files and didn't find your mentioned `url` as I already use `var server = <?php echo base_url(); ?>` in those files and lines.
